language: python
python:
- "3.7"

# command to install dependencies
install:
- pip install -r Ansible/test-requirements.txt
# command to run tests
script:
- ansible-lint Ansible/*.yml -x 303,701,601,206,602,403,301,502,305,306 -v
- yamllint --no-warnings k8s_resources/mission/*.yml