---
#
# This playbook switches the routing on Route53 BLUE/GREEN through the command -e "env=COLOR". 
#
- hosts: localhost
  gather_facts: false

  vars:
    zone_id: "Z0954889165W93WGCKIE8"
    zone_name: "arctiq-mission.com"
    zone_record: "arctiq-mission.com"
    state: "present"

  pre_tasks:
    - name: Display Ansible Playbook Python Path.
      debug:
        msg: "Python Interperter at: {{ ansible_playbook_python }}"

  tasks:
  - name: Generate Time Stamp.
    command: "date +%Y-%m-%d-%H-%M-%S"
    register: date_time

  - name: Switch to GREEN. A Record DNS Change.
    when: env == "green"
    route53:
      state: "{{ state }}"
      zone: "{{ zone_name }}"
      record: "{{ zone_record }}"
      type: A
      value: green.arctiq-mission.com
      alias: True
      alias_hosted_zone_id: "{{ zone_id }}" 
      overwrite: true

  - name: Switch to BLUE.
    when: env == "blue"
    route53:
      state: "{{ state }}"
      zone: "{{ zone_name }}"
      record: "{{ zone_record }}"
      type: A
      value: blue.arctiq-mission.com
      alias: True
      alias_hosted_zone_id: "{{ zone_id }}"
      overwrite: true

  - name: Set TXT Record Reflecting DNS Change.
    route53:
      state: "{{ state }}"
      zone: "{{ zone_name }}"
      record: "arctiq-mission.com"
      type: TXT
      ttl: 300
      value: '"BLUE/GREEN Switched to *!* {{ env | string}} *!* at {{ date_time.stdout | string}}"'
      overwrite: true